"""add partial_sections to tasks

Revision ID: 0dc51bf70906
Revises: 048a04fb667d
Create Date: 2026-08-06 05:03:34.389415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dc51bf70906'
down_revision: Union[str, Sequence[str], None] = '048a04fb667d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('partial_sections', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'partial_sections')
    # ### end Alembic commands ###
