"""add_screenshot_cache_and_gallery

Revision ID: b58bb7a19939
Revises: 0dc51bf70906
Create Date: 2026-08-06 17:57:31.985101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b58bb7a19939'
down_revision: Union[str, Sequence[str], None] = '0dc51bf70906'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('screenshot_caches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('screenshot_url', sa.String(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_screenshot_caches_id'), 'screenshot_caches', ['id'], unique=False)
    op.create_index(op.f('ix_screenshot_caches_url'), 'screenshot_caches', ['url'], unique=False)
    op.add_column('reports', sa.Column('screenshot_gallery', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'screenshot_gallery')
    op.drop_index(op.f('ix_screenshot_caches_url'), table_name='screenshot_caches')
    op.drop_index(op.f('ix_screenshot_caches_id'), table_name='screenshot_caches')
    op.drop_table('screenshot_caches')
    # ### end Alembic commands ###
