"""add_language_to_task

Revision ID: c1d0f1f1c1dc
Revises: b58bb7a19939
Create Date: 2026-08-06 18:13:17.250271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1d0f1f1c1dc'
down_revision: Union[str, Sequence[str], None] = 'b58bb7a19939'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('language', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'language')
    # ### end Alembic commands ###
